version: 1.0.{build}

skip_tags: true

configuration: Release

assembly_info:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  
platform: Any CPU

environment:
 COVERALLS_REPO_TOKEN:  
  secure: oxB2l7vHmBZHBJbl8pFZIGUao5m426LkQInK8WFv235cjMPLzPR+Wz3mdbYTSawM

before_build:
 - nuget restore ".\CoreSWOAS\Tests\CoreSWOAS.Business.Tests\CoreSWOAS.Business.Tests.csproj"
  
build:
  project: CoreSWOAS/Tests/CoreSWOAS.Business.Tests/CoreSWOAS.Business.Tests.csproj
  verbosity: detailed
