version: 1.0.{build}

skip_tags: true

configuration: Release
  
platform: Any CPU

before_build:
 - nuget restore ".\CoreSWOAS\Tests\CoreSWOAS.Business.Tests\CoreSWOAS.Business.Tests.csproj"
  
build:
  project: CoreSWOAS/Tests/CoreSWOAS.Business.Tests/CoreSWOAS.Business.Tests.csproj
  verbosity: detailed
