version: 1.0.{build}

skip_tags: true

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
platform: Any CPU

environment:
 COVERALLS_REPO_TOKEN:  
  secure: oxB2l7vHmBZHBJbl8pFZIGUao5m426LkQInK8WFv235cjMPLzPR+Wz3mdbYTSawM

before_build:
 - nuget restore ".\CoreSWOAS\CoreSWOAS.sln"
  
build:
  project: CoreSWOAS/CoreSWOAS.sln
  verbosity: detailed